
version: '3.3'

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: /home/bog/Desktop/Data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: /home/bog/Desktop/Data/db

networks:
  my-net:
    driver: bridge
 
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
       - my-net
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: always
    tty:
      true

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - my-net
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    tty: true

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - my-net
    restart: always
    depends_on:
      - wordpress